# This file was generated by GoReleaser. DO NOT EDIT.
class Strongbox < Formula
  desc "Securely store secrets at rest using Hashicorp Vault"
  homepage "https://github.com/mvisonneau/strongbox"
  version "0.1.7"

  if OS.mac?
    url "https://github.com/mvisonneau/strongbox/releases/download/0.1.7/strongbox_0.1.7_darwin_amd64.tar.gz"
    sha256 "ebea37bc6ddddf3884ab7b2c233e6bd3178f8b87dfa051eb72ba3727b6a57254"
  elsif OS.linux?
    url "https://github.com/mvisonneau/strongbox/releases/download/0.1.7/strongbox_0.1.7_linux_amd64.tar.gz"
    sha256 "8b8bb37285606e6533c7b6fa631959628e949eb286f0667e3cf1ac2448e95a72"
  end

  def install
    bin.install "strongbox"
  end
end
