# This file was generated by GoReleaser. DO NOT EDIT.
cask "gitlab-ci-pipelines-exporter" do
  name "gitlab-ci-pipelines-exporter"
  desc "GitLab CI pipelines exporter (prometheus/open-metrics)"
  homepage "https://github.com/mvisonneau/gitlab-ci-pipelines-exporter"
  version "0.6.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "gitlab-ci-pipelines-exporter"
  bash_completion "helpers/autocomplete/bash"
  zsh_completion "helpers/autocomplete/zsh"
  fish_completion "helpers/autocomplete/fish"

  on_macos do
    on_intel do
      url "https://github.com/mvisonneau/gitlab-ci-pipelines-exporter/releases/download/v#{version}/gitlab-ci-pipelines-exporter_v#{version}_darwin_amd64.tar.gz"
      sha256 "07ccca6ba5da215328787968a36b5ba4a4c2b81b11779944936b9b5d7c866a1e"
    end
    on_arm do
      url "https://github.com/mvisonneau/gitlab-ci-pipelines-exporter/releases/download/v#{version}/gitlab-ci-pipelines-exporter_v#{version}_darwin_arm64.tar.gz"
      sha256 "2df5fd9f6defb3534e3c9e417103d28dd4f29c9a9a6e98839ed130fffc2ba357"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/mvisonneau/gitlab-ci-pipelines-exporter/releases/download/v#{version}/gitlab-ci-pipelines-exporter_v#{version}_linux_amd64.tar.gz"
      sha256 "6c83cc99278c02d675768b6dc8a59477aea0e82991d76cbfe0ff658321ead2c7"
    end
    on_arm do
      url "https://github.com/mvisonneau/gitlab-ci-pipelines-exporter/releases/download/v#{version}/gitlab-ci-pipelines-exporter_v#{version}_linux_arm64.tar.gz"
      sha256 "0ac09c1733a1da1d99e7d32e99d358ac1ddd66512ade91684043f26ac41e0c18"
    end
  end

  # No zap stanza required
end
