# This file was generated by GoReleaser. DO NOT EDIT.
cask "s5" do
  desc "Safely Store Super Sensitive Stuff"
  homepage "https://github.com/mvisonneau/s5"
  version "0.2.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "s5"
  bash_completion "helpers/autocomplete/bash"
  zsh_completion "helpers/autocomplete/zsh"
  fish_completion "helpers/autocomplete/fish"

  on_macos do
    on_intel do
      url "https://github.com/mvisonneau/s5/releases/download/v0.2.0/s5_v0.2.0_darwin_amd64.tar.gz"
      sha256 "16c423b0623c78bbda61c8a3d7080da4f5143b44d869978277774b04dc795f23"
    end
    on_arm do
      url "https://github.com/mvisonneau/s5/releases/download/v0.2.0/s5_v0.2.0_darwin_arm64.tar.gz"
      sha256 "71b471b0dfb883564442d349a959d195ef4e32776b67013eb2e7d3cf8ef786a9"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/mvisonneau/s5/releases/download/v0.2.0/s5_v0.2.0_linux_amd64.tar.gz"
      sha256 "0373ffeecbc36c545534b76aa39635e46440ec4ba4cc2949f4378015240d810d"
    end
    on_arm do
      url "https://github.com/mvisonneau/s5/releases/download/v0.2.0/s5_v0.2.0_linux_arm64.tar.gz"
      sha256 "9ff39349fd16c424e570bae692437d812da6add7fbc17f5425f86d80884e2b9c"
    end
  end

  # No zap stanza required
end
