# This file was generated by GoReleaser. DO NOT EDIT.
class Ahs < Formula
  desc "Amazon EC2 Hostname Setter"
  homepage "https://github.com/mvisonneau/ahs"
  version "0.2.5"
  bottle :unneeded

  if OS.mac?
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/mvisonneau/ahs/releases/download/v0.2.5/ahs_v0.2.5_linux_amd64.tar.gz"
      sha256 "84015ce721cc2f343b31537a2209d7b7002f62eb6426f5c613323b2d8165707f"
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/mvisonneau/ahs/releases/download/v0.2.5/ahs_v0.2.5_linux_arm64.tar.gz"
        sha256 "345ba35a2909b5143cf34bb38c92943f4a8489062b98626e2e7aaf2eb0f446d9"
      else
      end
    end
  end

  def install
  end
end
