# This file was generated by GoReleaser. DO NOT EDIT.
class Approuvez < Formula
  desc "CLI helper to obtain live confirmation from people over Slack"
  homepage "https://github.com/mvisonneau/approuvez"
  version "0.1.0"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/mvisonneau/approuvez/releases/download/v0.1.0/approuvez_v0.1.0_darwin_amd64.tar.gz"
    sha256 "20ace3af8154ccf4f8a3cac15a9f334b0ef3530c0b25605563d551b6c6c6640c"
  end
  if OS.linux? && Hardware::CPU.intel?
    url "https://github.com/mvisonneau/approuvez/releases/download/v0.1.0/approuvez_v0.1.0_linux_amd64.tar.gz"
    sha256 "f1c271e91a1d622a7e1fc7009feba1df9ae0f8632a3c619386680c2476562d6d"
  end
  if OS.linux? && Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
    url "https://github.com/mvisonneau/approuvez/releases/download/v0.1.0/approuvez_v0.1.0_linux_arm64.tar.gz"
    sha256 "f3be56eaaddd1bc05cc84dcf53295fe21924914ea35c083dc52dbe84a03c6ed5"
  end

  def install
    bin.install "approuvez"
  end
end
