# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Approuvez < Formula
  desc "CLI helper to obtain live confirmation from people over Slack"
  homepage "https://github.com/mvisonneau/approuvez"
  version "0.1.1"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/mvisonneau/approuvez/releases/download/v0.1.1/approuvez_v0.1.1_darwin_amd64.tar.gz"
      sha256 "0116cdc815740b4e0f9fbca145d36e2870719d9736ab7ee39b6ef08d202cf005"

      def install
        bin.install "approuvez"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/mvisonneau/approuvez/releases/download/v0.1.1/approuvez_v0.1.1_darwin_arm64.tar.gz"
      sha256 "6bc566ba33605fc558d489f35cdd692cd7c75affee1d811b0f4eae7b175c5273"

      def install
        bin.install "approuvez"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/mvisonneau/approuvez/releases/download/v0.1.1/approuvez_v0.1.1_linux_arm64.tar.gz"
      sha256 "7ce873e56165e76c7fe3426573a0e040098e20ebc0d1a2bc933362bf46debf4c"

      def install
        bin.install "approuvez"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/mvisonneau/approuvez/releases/download/v0.1.1/approuvez_v0.1.1_linux_amd64.tar.gz"
      sha256 "9ec77eaa370633c3966dce759b79872816ec884ed2f6c741dd3aa15a6e9583b3"

      def install
        bin.install "approuvez"
      end
    end
  end
end
