# This file was generated by GoReleaser. DO NOT EDIT.
class Approuvez < Formula
  desc "CLI helper client to obtain live confirmation from relevant people"
  homepage "https://github.com/mvisonneau/approuvez"
  version "0.0.1"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/mvisonneau/approuvez/releases/download/v0.0.1/approuvez_v0.0.1_darwin_amd64.tar.gz"
    sha256 "787ebe063a0c9c06b9e516d6d69dd39e9f22546cef4e5d27e05408be904d60fb"
  end
  if OS.linux? && Hardware::CPU.intel?
    url "https://github.com/mvisonneau/approuvez/releases/download/v0.0.1/approuvez_v0.0.1_linux_amd64.tar.gz"
    sha256 "57b325fc0a2f6e203cd75182e9bf7025111b3b64b8471bf1045826ff698c15cb"
  end
  if OS.linux? && Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
    url "https://github.com/mvisonneau/approuvez/releases/download/v0.0.1/approuvez_v0.0.1_linux_arm64.tar.gz"
    sha256 "f4ab70dcb8106b42a0041323f09c4183a2026b2bf9f253b30876ba73737487e8"
  end

  def install
    bin.install "approuvez"
  end
end
