# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Automount < Formula
  desc "Dynamically mount available hard drives on Linux"
  homepage "https://github.com/mvisonneau/automount"
  version "0.1.1"
  bottle :unneeded
  depends_on :linux

  if OS.linux? && Hardware::CPU.intel?
    url "https://github.com/mvisonneau/automount/releases/download/v0.1.1/automount_v0.1.1_linux_amd64.tar.gz"
    sha256 "aebce0b874ef51f7c014ab34333f46cfbe9e3c339664679205db17b0e81db18c"
  end
  if OS.linux? && Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
    url "https://github.com/mvisonneau/automount/releases/download/v0.1.1/automount_v0.1.1_linux_arm64.tar.gz"
    sha256 "2e9880d32fa32bbcccc66b32e19e6e23725edd86d7f4d6228e7846c9d7321c3e"
  end

  def install
    bin.install "automount"
  end
end
