# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GitlabCiPipelinesExporter < Formula
  desc "GitLab CI pipelines exporter (prometheus/open-metrics)"
  homepage "https://github.com/mvisonneau/gitlab-ci-pipelines-exporter"
  version "0.5.6"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/mvisonneau/gitlab-ci-pipelines-exporter/releases/download/v0.5.6/gitlab-ci-pipelines-exporter_v0.5.6_darwin_arm64.tar.gz"
      sha256 "e85d20c8f9704e40cd1998038c65062a8b249edc2f1a292226a9855919e74a7b"

      def install
        bin.install "gitlab-ci-pipelines-exporter"
        bash_completion.install "./helpers/autocomplete/bash" => "gitlab-ci-pipelines-exporter"
        zsh_completion.install "./helpers/autocomplete/zsh" => "_gitlab-ci-pipelines-exporter"
        man1.install "./helpers/manpages/gitlab-ci-pipelines-exporter.1.gz"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/mvisonneau/gitlab-ci-pipelines-exporter/releases/download/v0.5.6/gitlab-ci-pipelines-exporter_v0.5.6_darwin_amd64.tar.gz"
      sha256 "f5f1042c8977dba66a4ef639307d93e288c243716bbcafd69d9cf804df47b864"

      def install
        bin.install "gitlab-ci-pipelines-exporter"
        bash_completion.install "./helpers/autocomplete/bash" => "gitlab-ci-pipelines-exporter"
        zsh_completion.install "./helpers/autocomplete/zsh" => "_gitlab-ci-pipelines-exporter"
        man1.install "./helpers/manpages/gitlab-ci-pipelines-exporter.1.gz"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/mvisonneau/gitlab-ci-pipelines-exporter/releases/download/v0.5.6/gitlab-ci-pipelines-exporter_v0.5.6_linux_arm64.tar.gz"
      sha256 "b70d7c34784cb74e6034ab1d08092b0d668eb40ec06e409d14ac5247d4012380"

      def install
        bin.install "gitlab-ci-pipelines-exporter"
        bash_completion.install "./helpers/autocomplete/bash" => "gitlab-ci-pipelines-exporter"
        zsh_completion.install "./helpers/autocomplete/zsh" => "_gitlab-ci-pipelines-exporter"
        man1.install "./helpers/manpages/gitlab-ci-pipelines-exporter.1.gz"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/mvisonneau/gitlab-ci-pipelines-exporter/releases/download/v0.5.6/gitlab-ci-pipelines-exporter_v0.5.6_linux_amd64.tar.gz"
      sha256 "efb30b543948b73b0309075fe7a38a34bd61ddfdc800e2bde6a1959dbaac3ddf"

      def install
        bin.install "gitlab-ci-pipelines-exporter"
        bash_completion.install "./helpers/autocomplete/bash" => "gitlab-ci-pipelines-exporter"
        zsh_completion.install "./helpers/autocomplete/zsh" => "_gitlab-ci-pipelines-exporter"
        man1.install "./helpers/manpages/gitlab-ci-pipelines-exporter.1.gz"
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/mvisonneau/gitlab-ci-pipelines-exporter/releases/download/v0.5.6/gitlab-ci-pipelines-exporter_v0.5.6_linux_armv6.tar.gz"
      sha256 "3f44defde439074e72f3df9e00f912d0542d8ebdae31cfba09f2b81354e76baa"

      def install
        bin.install "gitlab-ci-pipelines-exporter"
        bash_completion.install "./helpers/autocomplete/bash" => "gitlab-ci-pipelines-exporter"
        zsh_completion.install "./helpers/autocomplete/zsh" => "_gitlab-ci-pipelines-exporter"
        man1.install "./helpers/manpages/gitlab-ci-pipelines-exporter.1.gz"
      end
    end
  end

  test do
    system "#{bin}/gitlab-ci-pipelines-exporter -v"
  end
end
