# This file was generated by GoReleaser. DO NOT EDIT.
class GitlabCiPipelinesExporter < Formula
  desc "GitLab CI pipelines exporter (prometheus/open-metrics)"
  homepage "https://github.com/mvisonneau/gitlab-ci-pipelines-exporter"
  version "0.2.10"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/mvisonneau/gitlab-ci-pipelines-exporter/releases/download/0.2.10/gitlab-ci-pipelines-exporter_0.2.10_darwin_amd64.tar.gz"
    sha256 "e74c55a884bef11bf9cb335e6717b8c38f3ffe7b08e40fd121d865e7597d8713"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/mvisonneau/gitlab-ci-pipelines-exporter/releases/download/0.2.10/gitlab-ci-pipelines-exporter_0.2.10_linux_amd64.tar.gz"
      sha256 "43c08a55c339557268b1885aff09aafec5c14750254fac63d625efd193dcc2af"
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/mvisonneau/gitlab-ci-pipelines-exporter/releases/download/0.2.10/gitlab-ci-pipelines-exporter_0.2.10_linux_arm64.tar.gz"
        sha256 "d337f8bf86bbc37ce20f0e50615257f627835084fbb87d4db4239e8ca6db21ba"
      else
      end
    end
  end

  def install
    bin.install "gitlab-ci-pipelines-exporter"
  end
end
