# This file was generated by GoReleaser. DO NOT EDIT.
class GitlabMerger < Formula
  desc "Automated merge request creation for GitLab projects"
  homepage "https://github.com/mvisonneau/gitlab-merger"
  version "0.1.3"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/mvisonneau/gitlab-merger/releases/download/0.1.3/gitlab-merger_0.1.3_darwin_amd64.tar.gz"
    sha256 "d2be1137307b0b5453aaa405e0baaeb2059008d5b31089d2851a78969d0a74dd"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/mvisonneau/gitlab-merger/releases/download/0.1.3/gitlab-merger_0.1.3_linux_amd64.tar.gz"
      sha256 "675fe3c0fa9a760a446121ffff0abb3c5f1ca63df7b8a5b225dbcb478c348250"
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/mvisonneau/gitlab-merger/releases/download/0.1.3/gitlab-merger_0.1.3_linux_arm64.tar.gz"
        sha256 "7c503fadd9fd09fbf84d954b173b7d4fafc3d49a7c1ca0f73595708ca5721e90"
      else
      end
    end
  end

  def install
    bin.install "gitlab-merger"
  end
end
