# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GoEbsnvme < Formula
  desc "Fetch information about AWS EBS NVMe volumes"
  homepage "https://github.com/mvisonneau/go-ebsnvme"
  version "0.2.0"
  license "Apache-2.0"
  depends_on :linux

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/mvisonneau/go-ebsnvme/releases/download/v0.2.0/go-ebsnvme_v0.2.0_linux_arm64.tar.gz"
      sha256 "ff3d49a683fb5783ec3767ad212c7840296d1bb45a5bf6290bb194d0a9ef761b"

      def install
        bin.install "go-ebsnvme"
        bash_completion.install "./helpers/autocomplete/bash" => "go-ebsnvme"
        zsh_completion.install "./helpers/autocomplete/zsh" => "_go-ebsnvme"
        man1.install "./helpers/manpages/go-ebsnvme.1.gz"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/mvisonneau/go-ebsnvme/releases/download/v0.2.0/go-ebsnvme_v0.2.0_linux_amd64.tar.gz"
      sha256 "b941d68637abd440dfcc60e357b4b0d44cfb124896fde38b7ab0842611ecc571"

      def install
        bin.install "go-ebsnvme"
        bash_completion.install "./helpers/autocomplete/bash" => "go-ebsnvme"
        zsh_completion.install "./helpers/autocomplete/zsh" => "_go-ebsnvme"
        man1.install "./helpers/manpages/go-ebsnvme.1.gz"
      end
    end
  end

  test do
    system "#{bin}/go-ebsnvme -v"
  end
end
