# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GoEbsnvme < Formula
  desc "Fetch information about AWS EBS NVMe volumes"
  homepage "https://github.com/mvisonneau/go-ebsnvme"
  version "0.2.1"
  license "Apache-2.0"
  depends_on :linux

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/mvisonneau/go-ebsnvme/releases/download/v0.2.1/go-ebsnvme_v0.2.1_linux_arm64.tar.gz"
      sha256 "55095f16af35184e4b7c5be643888bc1e88f2e213fc10cafeb6e2cb82d26aba4"

      def install
        bin.install "go-ebsnvme"
        bash_completion.install "./helpers/autocomplete/bash" => "go-ebsnvme"
        zsh_completion.install "./helpers/autocomplete/zsh" => "_go-ebsnvme"
        man1.install "./helpers/manpages/go-ebsnvme.1.gz"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/mvisonneau/go-ebsnvme/releases/download/v0.2.1/go-ebsnvme_v0.2.1_linux_amd64.tar.gz"
      sha256 "9193037b54dbd5ea42276235490d29e61640e2ec2877daa03dcdb7f3072ff7a9"

      def install
        bin.install "go-ebsnvme"
        bash_completion.install "./helpers/autocomplete/bash" => "go-ebsnvme"
        zsh_completion.install "./helpers/autocomplete/zsh" => "_go-ebsnvme"
        man1.install "./helpers/manpages/go-ebsnvme.1.gz"
      end
    end
  end

  test do
    system "#{bin}/go-ebsnvme -v"
  end
end
