# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GoEbsnvme < Formula
  desc "Fetch information about AWS EBS NVMe volumes"
  homepage "https://github.com/mvisonneau/go-ebsnvme"
  version "0.1.4"
  license "Apache-2.0"
  depends_on :linux

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/mvisonneau/go-ebsnvme/releases/download/v0.1.4/go-ebsnvme_v0.1.4_linux_arm64.tar.gz"
      sha256 "9a6b00581f1baeb364ef7915ee5fe7e30db97bf796f708026dd246ccef4f42b8"

      def install
        bin.install "go-ebsnvme"
        bash_completion.install "./helpers/autocomplete/bash" => "go-ebsnvme"
        zsh_completion.install "./helpers/autocomplete/zsh" => "_go-ebsnvme"
        man1.install "./helpers/manpages/go-ebsnvme.1.gz"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/mvisonneau/go-ebsnvme/releases/download/v0.1.4/go-ebsnvme_v0.1.4_linux_amd64.tar.gz"
      sha256 "29007e38818ff5d7492cb2d3c5053259b1da5205459b11f9eae97ba9197b9c59"

      def install
        bin.install "go-ebsnvme"
        bash_completion.install "./helpers/autocomplete/bash" => "go-ebsnvme"
        zsh_completion.install "./helpers/autocomplete/zsh" => "_go-ebsnvme"
        man1.install "./helpers/manpages/go-ebsnvme.1.gz"
      end
    end
  end

  test do
    system "#{bin}/go-ebsnvme -v"
  end
end
