# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Gpcd < Formula
  desc "GoPro Cloud Downloader"
  homepage "https://github.com/mvisonneau/gpcd"
  version "0.0.1"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/mvisonneau/gpcd/releases/download/v0.0.1/gpcd_v0.0.1_darwin_amd64.tar.gz"
      sha256 "f55f3208963e3111306fb41667f3a3539e4fa95812ddea45ee221960827e5e31"

      def install
        bin.install "gpcd"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/mvisonneau/gpcd/releases/download/v0.0.1/gpcd_v0.0.1_darwin_arm64.tar.gz"
      sha256 "349bef9bfc95907481d60fb543ae8cc5c5f61f52d1eb672991bb0438a3804c86"

      def install
        bin.install "gpcd"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/mvisonneau/gpcd/releases/download/v0.0.1/gpcd_v0.0.1_linux_arm64.tar.gz"
      sha256 "16ad7aace72ff6a9deb60a3190f1562afd16076334ad8b43ce3857a0d3210820"

      def install
        bin.install "gpcd"
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/mvisonneau/gpcd/releases/download/v0.0.1/gpcd_v0.0.1_linux_armv6.tar.gz"
      sha256 "ca21ebea6629f0ba59a2429cc78f6432e422141080391a85aa18f7e0135e0724"

      def install
        bin.install "gpcd"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/mvisonneau/gpcd/releases/download/v0.0.1/gpcd_v0.0.1_linux_amd64.tar.gz"
      sha256 "f7654b74dc3b7b8c00cc8f9148ea067e1d27f70a9bdebadbd2021ed144515d36"

      def install
        bin.install "gpcd"
      end
    end
  end
end
