# This file was generated by GoReleaser. DO NOT EDIT.
class Mmds < Formula
  desc "Missed (AWS) Meta-Data (service)"
  homepage "https://github.com/mvisonneau/mmds"
  version "0.1.2"
  bottle :unneeded

  if OS.mac?
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/mvisonneau/mmds/releases/download/0.1.2/mmds_0.1.2_linux_amd64.tar.gz"
      sha256 "5d0af2a1ac338faa19148b1e932fc1ef60085f1f3e7e7ae55540272dee4bf28f"
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/mvisonneau/mmds/releases/download/0.1.2/mmds_0.1.2_linux_arm64.tar.gz"
        sha256 "4f9c1326dbe7919605abc55851968888f9c53671f3305ba9782b81e0a786ae95"
      else
      end
    end
  end

  def install
  end
end
