# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Mmds < Formula
  desc "Missed (AWS) Meta-Data (service)"
  homepage "https://github.com/mvisonneau/mmds"
  version "0.1.3"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/mvisonneau/mmds/releases/download/v0.1.3/mmds_v0.1.3_darwin_amd64.tar.gz"
      sha256 "2f9fbf852ce487dfe12b1934e0d6cbe8600eaa2be9cc45ed637e9b9300531124"

      def install
        bin.install "mmds"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/mvisonneau/mmds/releases/download/v0.1.3/mmds_v0.1.3_darwin_arm64.tar.gz"
      sha256 "86318c52c099c761c319f6752b98afe9f4b96b6199c6ee5793d9cd39c1448989"

      def install
        bin.install "mmds"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/mvisonneau/mmds/releases/download/v0.1.3/mmds_v0.1.3_linux_arm64.tar.gz"
      sha256 "5e587268bec7b778a4ea419fbea100a1735809c134f5b3fce5949e099cce20d1"

      def install
        bin.install "mmds"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/mvisonneau/mmds/releases/download/v0.1.3/mmds_v0.1.3_linux_amd64.tar.gz"
      sha256 "27c18d7b17a279ca041e52bdb805fc267c805b5eee9d8935880e3aaa3946a47a"

      def install
        bin.install "mmds"
      end
    end
  end
end
