# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Mmds < Formula
  desc "Missed (AWS) Meta-Data (service)"
  homepage "https://github.com/mvisonneau/mmds"
  version "0.1.5"

  on_macos do
    on_intel do
      url "https://github.com/mvisonneau/mmds/releases/download/v0.1.5/mmds_v0.1.5_darwin_amd64.tar.gz"
      sha256 "15ef54892f872dab320e8e028fd03d0e8ccdcd4320078f45a4a9426960d79581"

      def install
        bin.install "mmds"
      end
    end
    on_arm do
      url "https://github.com/mvisonneau/mmds/releases/download/v0.1.5/mmds_v0.1.5_darwin_arm64.tar.gz"
      sha256 "6770382310f17ed939e730b443916e4c8ce5a7e04b5be90fa863d7c11349d380"

      def install
        bin.install "mmds"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/mvisonneau/mmds/releases/download/v0.1.5/mmds_v0.1.5_linux_amd64.tar.gz"
        sha256 "4ff855f9df994c54bf3fb10bdf79c7549586416a52dcac87e9b40eef467326cc"

        def install
          bin.install "mmds"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/mvisonneau/mmds/releases/download/v0.1.5/mmds_v0.1.5_linux_arm64.tar.gz"
        sha256 "d7f33465fe1f0b2a44e8d02a4196a6281442802820da6235a847b1d47c6f497a"

        def install
          bin.install "mmds"
        end
      end
    end
  end
end
