# This file was generated by GoReleaser. DO NOT EDIT.
class Ocalver < Formula
  desc "Opinionated CalVer generator"
  homepage "https://github.com/mvisonneau/ocalver"
  version "0.0.4"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/mvisonneau/ocalver/releases/download/v0.0.4/ocalver_v0.0.4_darwin_amd64.tar.gz"
    sha256 "09c31b1f3d06d972a261c3745e0aaec25da14fbc62ea8d255d892e79135a10d2"
  end
  if OS.linux? && Hardware::CPU.intel?
    url "https://github.com/mvisonneau/ocalver/releases/download/v0.0.4/ocalver_v0.0.4_linux_amd64.tar.gz"
    sha256 "d664a1fb985d2d4b93753f8cf5608a2a3b3cc60bf6208b81da891539a7d48d28"
  end
  if OS.linux? && Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
    url "https://github.com/mvisonneau/ocalver/releases/download/v0.0.4/ocalver_v0.0.4_linux_arm64.tar.gz"
    sha256 "d45b87d9abbb59e9b86df6390c88da5ea4ae0c4d640dc669e05041bb5ec2584a"
  end

  def install
    bin.install "ocalver"
  end
end
