# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ocalver < Formula
  desc "Opinionated CalVer generator"
  homepage "https://github.com/mvisonneau/ocalver"
  version "0.0.4-9-gb800c8d"
  bottle :unneeded

  if OS.mac? && Hardware::CPU.intel?
    url "https://github.com/mvisonneau/ocalver/releases/download/v0.0.4-9-gb800c8d/ocalver_v0.0.4-9-gb800c8d_darwin_amd64.tar.gz"
    sha256 "9bf2d8df3ade17e0c5a0307c97ac7d850dbea7eb7a781f9fc60d60e373aca65d"
  end
  if OS.mac? && Hardware::CPU.arm?
    url "https://github.com/mvisonneau/ocalver/releases/download/v0.0.4-9-gb800c8d/ocalver_v0.0.4-9-gb800c8d_darwin_arm64.tar.gz"
    sha256 "f1d9339180b46b602ae6de85fd4a5c78b49acd51970d30936fcec877736f082a"
  end
  if OS.linux? && Hardware::CPU.intel?
    url "https://github.com/mvisonneau/ocalver/releases/download/v0.0.4-9-gb800c8d/ocalver_v0.0.4-9-gb800c8d_linux_amd64.tar.gz"
    sha256 "ffd9b265472a22941f8ca069bb8c0bad4e620e68eeb2388acd5ee34ab6517d3d"
  end
  if OS.linux? && Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
    url "https://github.com/mvisonneau/ocalver/releases/download/v0.0.4-9-gb800c8d/ocalver_v0.0.4-9-gb800c8d_linux_arm64.tar.gz"
    sha256 "612bbf5016e882c743f8befb21baa8dc7ea9bf11e5f6ffbed56601ec371ffda4"
  end

  def install
    bin.install "ocalver"
  end
end
