# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class SlackGitCompare < Formula
  desc "Compare git references within Slack"
  homepage "https://github.com/mvisonneau/slack-git-compare"
  version "0.1.1"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/mvisonneau/slack-git-compare/releases/download/v0.1.1/slack-git-compare_v0.1.1_darwin_arm64.tar.gz"
      sha256 "55536b92f024ef7bed570771c1bb41676c232df0605e303f9fee9f2c8473a5c4"

      def install
        bin.install "slack-git-compare"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/mvisonneau/slack-git-compare/releases/download/v0.1.1/slack-git-compare_v0.1.1_darwin_amd64.tar.gz"
      sha256 "b00c21e8f075bfdd68216dcc820aa6b2225ad3f86826153bfe8b207c44ab7da2"

      def install
        bin.install "slack-git-compare"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/mvisonneau/slack-git-compare/releases/download/v0.1.1/slack-git-compare_v0.1.1_linux_amd64.tar.gz"
      sha256 "273bc26a3488c9d4cd4c290cb16d766c95d49ac74cb29c1c935725bc63272a0d"

      def install
        bin.install "slack-git-compare"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/mvisonneau/slack-git-compare/releases/download/v0.1.1/slack-git-compare_v0.1.1_linux_arm64.tar.gz"
      sha256 "a064ccdaeb13252968357f20ab358124db37b6a6dea1ab269ac6ed1a478cfdea"

      def install
        bin.install "slack-git-compare"
      end
    end
  end
end
