# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class SlackGitCompare < Formula
  desc "Compare git references within Slack"
  homepage "https://github.com/mvisonneau/slack-git-compare"
  version "0.0.1"
  bottle :unneeded

  if OS.mac? && Hardware::CPU.intel?
    url "https://github.com/mvisonneau/slack-git-compare/releases/download/v0.0.1/slack-git-compare_v0.0.1_darwin_amd64.tar.gz"
    sha256 "75768f5d508189413ce22ad72aa29d4acfddaef5ca2a2e94761eabeeff9a7ba4"
  end
  if OS.mac? && Hardware::CPU.arm?
    url "https://github.com/mvisonneau/slack-git-compare/releases/download/v0.0.1/slack-git-compare_v0.0.1_darwin_arm64.tar.gz"
    sha256 "53db0fd756ce1453de475de4a53c3921cddce9cb6c69e5bdd1542481054c9b88"
  end
  if OS.linux? && Hardware::CPU.intel?
    url "https://github.com/mvisonneau/slack-git-compare/releases/download/v0.0.1/slack-git-compare_v0.0.1_linux_amd64.tar.gz"
    sha256 "dc4b58ecee599d86f1b778e175acae08e437f190b6b43ebf9ec77a9a050b7f72"
  end
  if OS.linux? && Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
    url "https://github.com/mvisonneau/slack-git-compare/releases/download/v0.0.1/slack-git-compare_v0.0.1_linux_arm64.tar.gz"
    sha256 "722b37cfa918da8ed66c98962a8fac2072b70c4c256693b6062bb9123d75770b"
  end

  def install
    bin.install "slack-git-compare"
  end
end
