# This file was generated by GoReleaser. DO NOT EDIT.
class Strongbox < Formula
  desc "Safely manage Hashicorp Vault secrets at rest"
  homepage "https://github.com/mvisonneau/strongbox"
  version "0.2.0"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/mvisonneau/strongbox/releases/download/0.2.0/strongbox_0.2.0_darwin_amd64.tar.gz"
    sha256 "80412c52d162e86f61f7d2e3d055a8c8ed7db917f43075b753c09eca3e1793ef"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/mvisonneau/strongbox/releases/download/0.2.0/strongbox_0.2.0_linux_amd64.tar.gz"
      sha256 "47761b4ed4d14539c3fdccec507f4e285cefc05dda65ea459c5ca60e68d1d690"
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/mvisonneau/strongbox/releases/download/0.2.0/strongbox_0.2.0_linux_arm64.tar.gz"
        sha256 "8fb2b229102bc6fd174a28be9ab15a9e158e2dd3f36d9a64fd0bd6450f5957de"
      else
      end
    end
  end

  def install
    bin.install "strongbox"
  end
end
