# This file was generated by GoReleaser. DO NOT EDIT.
class Tfcw < Formula
  desc "Safely Store Super Sensitive Stuff"
  homepage "https://github.com/mvisonneau/s5"
  version "0.0.2"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/mvisonneau/tfcw/releases/download/0.0.2/tfcw_0.0.2_darwin_amd64.tar.gz"
    sha256 "5ba841436ab7a5f85a8a9d2ebd0925ee83368b053d0140794f2f935c6839098a"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/mvisonneau/tfcw/releases/download/0.0.2/tfcw_0.0.2_linux_amd64.tar.gz"
      sha256 "02dafccd536d2d5f4d74d2e74ab02f66fd6c732bc00c50c47f71ed4475ba1cc6"
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/mvisonneau/tfcw/releases/download/0.0.2/tfcw_0.0.2_linux_arm64.tar.gz"
        sha256 "cd8efad8e3cb3244350f81ffd03073c827b046e0f1766ba4a0c7506d2b7a1aed"
      else
      end
    end
  end

  def install
    bin.install "tfcw"
  end
end
