# This file was generated by GoReleaser. DO NOT EDIT.
class Tfcw < Formula
  desc "Terraform Cloud Wrapper"
  homepage "https://github.com/mvisonneau/tfcw"
  version "0.0.10"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/mvisonneau/tfcw/releases/download/v0.0.10/tfcw_0.0.10_darwin_amd64.tar.gz"
    sha256 "c546883acdbf2a28f62c4756be597fe8cdf0c6be01501f7da5a5a5414ea0bc81"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/mvisonneau/tfcw/releases/download/v0.0.10/tfcw_0.0.10_linux_amd64.tar.gz"
      sha256 "042d79fd2f93dc9285c803cbd44d97e1b51886fbdbbbf0f1f08935002c160bcb"
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/mvisonneau/tfcw/releases/download/v0.0.10/tfcw_0.0.10_linux_arm64.tar.gz"
        sha256 "2f47109c451f23a752640acf9edf30ed24794dbb0b845bd616ac9b6dd6f95d50"
      else
      end
    end
  end

  def install
    bin.install "tfcw"
  end
end
