# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Vac < Formula
  desc "VAC - Vault AWS Credentials Manager"
  homepage "https://github.com/mvisonneau/vac"
  version "0.0.9"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/mvisonneau/vac/releases/download/v0.0.9/vac_v0.0.9_darwin_amd64.tar.gz"
      sha256 "f708c5af99f8753ed35f567658b7c6875b03212f6902ee550c2c2123ccb2ad0c"

      def install
        bin.install "vac"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/mvisonneau/vac/releases/download/v0.0.9/vac_v0.0.9_darwin_arm64.tar.gz"
      sha256 "eb06de7d9c7579d48949a25f03e7dc43115da03f6152f1687f9615a12adfe672"

      def install
        bin.install "vac"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/mvisonneau/vac/releases/download/v0.0.9/vac_v0.0.9_linux_amd64.tar.gz"
      sha256 "75f3665f74fdc78590653f7d6b7587eb70b0b939760dff430eea9dd28f638bdf"

      def install
        bin.install "vac"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/mvisonneau/vac/releases/download/v0.0.9/vac_v0.0.9_linux_arm64.tar.gz"
      sha256 "3ecdf5d4102d92c1ad663d28e781540fa1a6e89f84752e3828e15c798d659344"

      def install
        bin.install "vac"
      end
    end
  end
end
