# This file was generated by GoReleaser. DO NOT EDIT.
class Vac < Formula
  desc "VAC - Vault AWS Credentials Manager"
  homepage "https://github.com/mvisonneau/vac"
  version "0.0.2"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/mvisonneau/vac/releases/download/0.0.2/vac_0.0.2_darwin_amd64.tar.gz"
    sha256 "66be08fbe43b61787157aa675f9752d34b49994377a1636f14e1cd52f37a1a61"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/mvisonneau/vac/releases/download/0.0.2/vac_0.0.2_linux_amd64.tar.gz"
      sha256 "12d04183fe185721a1c4073777725f67a10865daf5ca01671766b53d7c5a92c5"
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/mvisonneau/vac/releases/download/0.0.2/vac_0.0.2_linux_arm64.tar.gz"
        sha256 "c1cf81353f4b18852ff3fd3539fa6d440549d82da45c8b9cbd473814333b9530"
      else
      end
    end
  end

  def install
    bin.install "vac"
  end
end
